name: build_deps

on:
  workflow_dispatch:
    inputs:
      buildWindows:
        description: 'Windows Build'
        type: boolean
        default: true
        required: false
      buildAmd64:
        description: 'amd64'
        type: boolean
        default: true
        required: false
      buildArm64:
        description: 'arm64'
        type: boolean
        default: false
        required: false
      buildUpload:
        description: 'Upload Build Artifacts'
        type: boolean
        default: true
        required: false
      buildMac:
        description: 'Mac Build'
        type: boolean
        default: false
        required: false
      buildConfig:
        description: 'Build Config'
        required: false
        default: 'Release'
        type: choice
        options:
          - Release
          - Debug


jobs:
  ffmpeg-macos-build:
    name: Build FFmpeg for macOS
    runs-on: macos-15
    if: github.event.inputs.buildMac == 'true'
    strategy:
      fail-fast: true
      matrix:
        target: [macos-arm64, macos-x86_64]
        arm64:
          - ${{ inputs.buildArm64 }}
        amd64:
          - ${{ inputs.buildAmd64 }}
        include:
          - target: macos-arm64
            config: ${{ inputs.buildConfig }}
            type: static
          - target: macos-x86_64
            config: ${{ inputs.buildConfig }}
            type: static
        exclude:
          - target: x64
            amd64: false
          - target: arm64
            arm64: false
    defaults:
      run:
        shell: zsh --no-rcs --errexit --pipefail {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Environment
        id: setup
        run: |
          print '::group::Enable Xcode 16.1'
          sudo xcode-select --switch /Applications/Xcode_16.1.0.app/Contents/Developer
          print '::endgroup::'
          local -a unwanted_formulas=(llvm gcc postgresql openjdk sox libsndfile flac libvorbis opusfile \
            libogg composer php gd freetype fontconfig webp libpng lame libtiff opus kotlin \
            sbt libxft libxcb pkg-config@0.29.2)
          local -a remove_formulas=()
          for formula (${unwanted_formulas}) {
            if [[ -d ${HOMEBREW_PREFIX}/Cellar/${formula} ]] remove_formulas+=(${formula})
          }
          if (( #remove_formulas )) brew uninstall --ignore-dependencies ${remove_formulas}
          local -r date_string=$(date +"%Y-%m-%d")
          local -r target='${{ matrix.target }}'
          artifact_name="ffmpeg-${target}-${{ github.sha }}"
          file_name="${target%%-*}-ffmpeg-${date_string}-${target##*-}.tar.xz"
          dsym_artifact_name="ffmpeg-${target}-dSYMs-${{ github.sha }}"
          dsym_file_name="${target%%-*}-ffmpeg-${date_string}-${target##*-}-dSYMs.tar.xz"
          print "artifactName=${artifact_name}" >> $GITHUB_OUTPUT
          print "artifactFileName=${file_name}" >> $GITHUB_OUTPUT
          print "dsymArtifactName=${dsym_artifact_name}" >> $GITHUB_OUTPUT
          print "dsymArtifactFileName=${dsym_file_name}" >> $GITHUB_OUTPUT
          print "ccacheDate=${date_string}" >> $GITHUB_OUTPUT
      - name: Build FFmpeg
        uses: ./.github/actions/build-ffmpeg
        with:
          target: ${{ matrix.target }}
          type: ${{ matrix.type }}
          config: ${{ matrix.config }}

      - name: Publish Build Artifacts
        if: github.event.inputs.buildUpload == 'true'
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.setup.outputs.artifactName }}
          path: ${{ github.workspace }}/${{ matrix.target }}/${{ steps.setup.outputs.artifactFileName }}


  ffmpeg-windows-build:
    name: Build FFmpeg for Windows
    runs-on: windows-2022
    if: github.event.inputs.buildWindows == 'true'
    strategy:
      fail-fast: true
      matrix:
        target: [x64, arm64]
        arm64:
          - ${{ inputs.buildArm64 }}
        amd64:
          - ${{ inputs.buildAmd64 }}
        include:
          - target: x64
            config: ${{ inputs.buildConfig }}
            type: static
          - target: arm64
            config: ${{ inputs.buildConfig }}
            type: static
        exclude:
          - target: x64
            amd64: false
          - target: arm64
            arm64: false
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Environment
        id: setup
        run: |
          # Setup Environment
          $Target='${{ matrix.target }}'
          $ArtifactName="ffmpeg-windows-${Target}-${{ github.sha }}"
          $FileName="windows-ffmpeg-$(Get-Date -Format 'yyyy-MM-dd')-${Target}.zip"
          "artifactName=${ArtifactName}" >> $env:GITHUB_OUTPUT
          "artifactFileName=${FileName}" >> $env:GITHUB_OUTPUT
      - name: Build FFmpeg
        uses: ./.github/actions/build-ffmpeg
        with:
          target: ${{ matrix.target }}
          type: ${{ matrix.type }}
          config: ${{ matrix.config }}

      - name: Publish Build Artifacts
        if: github.event.inputs.buildUpload == 'true'
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.setup.outputs.artifactName }}
          path: ${{ github.workspace }}\windows\${{ steps.setup.outputs.artifactFileName }}
